#!/bin/sh
set -e

/var/jb/usr/bin/launchctl bootstrap system /var/jb/Library/LaunchDaemons/com.rileytestut.altdaemon.plist
/var/jb/usr/bin/launchctl kickstart -k user/foreground/com.rileytestut.altdaemon
